[project]
name = "simclr-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "jupyter>=1.1.1",
    "lightly>=1.5.21",
    "matplotlib>=3.7.5",
    "notebook>=7.3.3",
    "scikit-learn>=1.3.2",
    "tqdm>=4.67.1",
]
